### ISSUE TITLE
Money view

### ISSUE THREAD

**Issue by ezraholm50** [gurbyz/power-wheel-card#21]
Hello! thanks for the great card.

I'm having trouble viewing the money view. Its not there...

This is my config, i thought i've done everything stated in the docs.

```
      - type: custom:power-wheel-card
        title_power: "Power distribution"
        title_energy: "Energy distribution"
        title_money: "Energy costs/savings"
        solar_energy_entity: sensor.victron_pv_energy
        solar_power_entity: sensor.pv_power_production
        grid_power_consumption_entity: sensor.grid_power_consumption
        grid_power_production_entity: sensor.grid_power_production
        grid_energy_consumption_entity: sensor.daily_energy_consumption
        grid_energy_production_entity: sensor.daily_energy_production
        energy_consumption_rate: 0.22
        energy_production_rate: 0.20
        money_unit: "€"
        solar_icon: "mdi:white-balance-sunny"
        grid_icon: "mdi:transmission-tower"
        home_icon: "mdi:home-assistant"
        power_decimals: 3
        energy_decimals: 3
        money_decimals: 2
        color_icons: true
        consuming_color: "#dd5500"
        producing_color: "#33ff33"
        initial_auto_toggle_view: false
```

**Comment by gurbyz** [comment]
At first glance I don't see abnormal things in your config, but you missed the issue template somehow. A completely filled in template could give more hints where it's going wrong. Could you supply the requested version info and the **Dev console debug output** info and past any errors you see in the console?

---

I have read the wiki about what to try first before creating a bug report.

**Which custom card does give you issues?**
power-wheel-card

**Which version of HA do you use?**

**Which version of the card do you use?**

**Describe the bug**
A clear and concise description of what the bug is. Paste any error messages.

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
  - type: "custom:power-wheel-card"
    solar_power_entity: sensor.solar_power
    ...etc...
```

**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.

Example: power-wheel-cardVersion: 0.0.10Lovelace resource: power-wheel-card.js?v=0.0.10HA version: 0.87.1Report issues here: ...etc...

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
