### ISSUE TITLE
Card doesn't load in 0.106 beta

### ISSUE THREAD

**Issue by VDRainer** [gurbyz/power-wheel-card#34]
I have read the wiki about what to try first before creating a bug report.

**Which custom card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
0.106.0b0

**Which version of the card do you use?**
Latest, fresh install 1 minute ago

**Describe the bug**
A clear and concise description of what the bug is. Paste any error messages.
![Auswahl_276](https://user-images.githubusercontent.com/26381449/74977784-afeb9400-542b-11ea-98aa-ca5bdc9d52e0.png)
I think related to:
https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
                type: "custom:power-wheel-card"
                title: Leistungsverteilung
                solar_power_entity: sensor.e3dc_battery_power_neg2pos
                grid_power_production_entity: sensor.e3dc_net_power_neg2pos_only
                grid_power_consumption_entity: sensor.e3dc_net_power_pos_only
                home_icon: mdi:home-outline
                solar_icon: mdi:car-battery
                grid_icon: mdi:transmission-tower
                color_icons: true
                consuming_color: var(--my-green)
                producing_color: var(--my-yellow)
```

**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.

Example: power-wheel-cardVersion: 0.0.10Lovelace resource: power-wheel-card.js?v=0.0.10HA version: 0.87.1Report issues here: ...etc...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gurbyz** [comment]
Thx for reporting this. I just prepared for the freezing config in version 0.0.16. But maybe the card also needs the helper functions? To be sure, can you add the `debug: true` parameter to your config and respond with what shows up in the console?

**Comment by VDRainer** [comment]
@gurbyz , thanks for looking at this.
Hope i did it right, but it shows absolutely nothing. Reloaded the browser with CTRL-F5
![Auswahl_277](https://user-images.githubusercontent.com/26381449/74981001-c72d8000-5431-11ea-96b3-031c6873f75d.png)

**Comment by gurbyz** [comment]
You probably did right, but the card breaks before putting things in the console. :-/ Strange thing is that this kind of error should have been solved by restructuring the `config` variable which is done in version 0.0.16. I want to be sure that you don't have version 0.0.15 in your cache, so that's why I wanted to see the console debug output. Sometimes even refreshing the browser doesn't help.

Let's try this. Could you find the source in the dev console like in the picture below? The version number is shown in the code here and should be 0.0.16.
![image](https://user-images.githubusercontent.com/3920372/74981810-3a83c180-5433-11ea-8bc7-bf65a8fdb7fc.png)

**Comment by VDRainer** [comment]
@gurbyz , so sorry, your card works.
I downloaded it with wget an got a power-wheel-card.js.2 file.
So stupid!

**Comment by gurbyz** [comment]
O, super. And no problem at all. And thx for testing the card in this beta version for me. Much appreciated.
