### ISSUE TITLE
Would we able to have home_power_entity please

### ISSUE THREAD

**Issue by meremortals70** [gurbyz/power-wheel-card#46]
The calculations of home power usage is floored when a battery is installed.

Could we please have a home_power_entity?

The Tesla Powerwall as an example has a load usage which represents the power the house is using.

Power is drawn from the solar panels first, then the battery to make up a deficit and then if necessary the grid to make up the current house load.

The current calculation does not account for the battery power being supplied.

The following might help:

1. This is what the powerwheel is showing
![image](https://user-images.githubusercontent.com/52735978/80787087-d3b81c80-8bc8-11ea-8c00-a9aca4bbccc8.png)

2. This is what the power system is actually doing.
![image](https://user-images.githubusercontent.com/52735978/80787122-edf1fa80-8bc8-11ea-918f-906fc684e430.png)

**Comment by gurbyz** [comment]
Hi, thx for posting this issue.

In version 0.1.0 battery support is implemented with a set of rules in mind. The ruleset is very basic and not complete as explained in the readme.

> 1. Solar power is consumed by home first.
> 2. What's left of solar power (after home did consume) is used for charging the battery.
> 3. What's left of solar power (after home and battery did consume) is produced to the grid.

So in fact it should have worked for you. Maybe the small amount of power that's imported from the grid is causing this effect with the card.

But it could also be something else: I see that your solar icon turns red when producing energy. Can you check if the solar power value is a positive number when producing solar power?

**Comment by gurbyz** [comment]
Closing because didn't get a response.

**Comment by meremortals70** [comment]
Sorry didn’t see your response.

The main issue I have is not the rules around solar, it’s around the calculation of home usage.

Can we have a home_entity is what I requested

**Comment by gurbyz** [comment]
You mean a home_entity so that the card will take the home value from that entity instead of calculate the value of the home entity? That's a feature request I won't implement, because the calculations should be that correct that users won't need that.

I suspect a misconfiguration in your setup. See my question earlier:
> I see that your solar icon turns red when producing energy. Can you check if the solar power value is a positive number when producing solar power?

That could be the reason why the calculated value for Home seems wrong to you. According to your screenshots you off course want to see Home = 0.3 + 1.8 = 2.1 But since signs of values are not shown in the card, the calculation could be -0.3 + 1.8 = 1.5 or even 0.3 + -1.8 = -1.5 Correct calculations depend on correct configuration and especially on the polarity of each input.

**Comment by meremortals70** [comment]
By your own definition 

Calculates the current power that you nett consume from the grid: grid power. Input for the calculation is the power that you consume from the grid and the power that you produce to the grid.

By adding the battery into the power wheel, it breaks the current power calculation.

You have other optional entities So why not this one?

**Comment by meremortals70** [comment]
So here are a few more scenarios, with the card right next to my Tesla Powerwall Two sensors so you can see for yourself where the issue lies. I have also included my config below.

I have removed the other two "pages" until we can resolve the initial issues.

![image](https://user-images.githubusercontent.com/52735978/83093465-d849f500-a0e2-11ea-8ad4-cee29535a096.png)

![image](https://user-images.githubusercontent.com/52735978/83093336-98830d80-a0e2-11ea-8a7e-2d24870aadd5.png)

![image](https://user-images.githubusercontent.com/52735978/83093663-34ad1480-a0e3-11ea-8739-05a697ec4542.png)

![image](https://user-images.githubusercontent.com/52735978/83093745-5efed200-a0e3-11ea-891a-5107368edad2.png)

![image](https://user-images.githubusercontent.com/52735978/83093816-835aae80-a0e3-11ea-820d-dad369f9da34.png)

![image](https://user-images.githubusercontent.com/52735978/83093883-ab4a1200-a0e3-11ea-8576-bc89b5463c2e.png)

I was disappointed in the attitude displayed in your response as you actually had asked for help to get it right.

**Comment by meremortals70** [comment]
Oh and the calculations are not the best way if you have the sensors available as the calculation doesn't take efficiencies of the system.  There are losses in conversion from DC-AC-DC-AC in the system,

**Comment by meremortals70** [comment]
Sun just came out so another example

![image](https://user-images.githubusercontent.com/52735978/83095416-a6d32880-a0e6-11ea-8f24-2cab5feb676b.png)

**Comment by gurbyz** [comment]
Thx for being so complete in your response. By supplying your config and the screenshots you have answered my initial question and I can rule out some things like an inverted polarity of the solar sensor.

About the screenshots in your last response. Let's start with the second screenshot. That one is interesting. When I say 'seems correct to me' I mean that the values and arrows seem to obey the ruleset written in my first response. (I don't own a battery, so I defined some rules together with users that have a battery.) Conversion losses were no part of any rules yet I have to admit.

**About screenshot nr 2**
This screenshot seems correct to me. I see a battery discharging at 1.48 kW. And the home is using almost all of it. Not all of it, because all power from the solar panels goes first in the ruleset. I see a discrepancy for the value of the home icon. To me 3.414 kW seems correct. You seem to expect 0.462 kW there? 
**Question:** Is that a correct assumption and if so can you explain why you expect to see 0.462 kW there?

Of course it's weird that the battery is represented two times, but that's due to the current layout. Maybe I should show more explicitly that there is only 0.050 kW flowing from (left) battery icon to grid icon. The arrow value is hidden now, but that's because of other users not wanting to see duplicate values in their card. (Arrow values only appear when they are not equal to the source icon nor destination icon).

**About the screenshot in your first message**
The solar icon is red in this screenshot and I can't understand that comparing it to your more recent screenshots. That means the value of your solar entity was *negative* 0.308 kW at that point in time. (There's no calculation going on in the background and the value of the entity is set directly to the icon.)
**Question:** In what scenario does your solar entity turns to this negative kind of values?

**Comment by meremortals70** [comment]
In all the screenshots the powerwall results are correct. They are sensors generated by the a Tesla Powerwall Add-in for HA.

The powerwall sensor for the battery is the reverse of your assumptions for charging.

This is why I suggested an option true/false for battery similar to production is possible. A false option here would reverse the “flow” 

ie. in the second screen shot the battery is being charged by the solar panels with the residual power not used by the house.

With the Tesla Battery there is always some “leakage” from and to the grid. Tesla say it’s for frequency sync and demand management. Anyway that’s another discussion.

If you reverse these battery charge/discharge figures the math works.

**Comment by gurbyz** [comment]
Great to have that sorted out. :-) . I'll make an extra input parameter for the polarity of the battery sensor so people don't have to create an extra template sensor.

In the meantime you could use a workaround to comply to the requirements of the card. You probably know how to setup a template sensor for this that reversed the polarity. But if you don't, this should help:
```
sensor:
  - platform: template
    sensors:
      new_battery_power:
        friendly_name: Battery
        unit_of_measurement: 'kW'
        value_template: >-
          {{ 0 - states('sensor.original_battery_power') | float }}
```

**Comment by meremortals70** [comment]
Thanks I had forgotten about template sensors. It’s now looking much better

**Comment by gurbyz** [comment]
There is a `charging_is_positive` parameter now. You can set it to `false` and remove your extra template sensor.

**Comment by meremortals70** [comment]
Thank you?
