### ISSUE TITLE
No Auto Toggle

### ISSUE THREAD

**Issue by PierreScerri** [gurbyz/power-wheel-card#73]
I have read the wiki about what to try first before creating a bug report.

**Which version of HA do you use?**
2021.1.4
**Which version of the card do you use?**
0.1.5
**Describe the bug**
A clear and concise description of what the bug is. Paste any error messages.
Is it possible to turn off the auto toggle feature and just switch view when clicked?

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
color_icons: true
consuming_color: 'var(--label-badge-yellow, #f4b400)'
debug: false
energy_decimals: 2
grid_energy_consumption_entity: sensor.daily_import
grid_energy_production_entity: sensor.daily_export
grid_power_consumption_entity: sensor.import_power
grid_power_production_entity: sensor.export_power
home_icon: 'mdi:home-assistant'
title_power: Power Now
title_energy: Energy Today
initial_auto_toggle_view: false
initial_view: energy
power_decimals: 0
auto_toggle_view_period: 0
producing_color: 'var(--label-badge-green, #0da035)'
production_is_positive: 1
solar_energy_entity: sensor.daily_solar
solar_icon: 'mdi:solar-power'
solar_power_entity: sensor.sdm120power
type: 'custom:power-wheel-card'

```

**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.
N/A

**Expected behavior**
N/A
**Screenshots**
N/A
**Additional context**
N/A

**Comment by gurbyz** [comment]
That should be possible. And even with your current config that should already be the case. So I don't understand exactly what the issue is. I tried to reproduce the issue with your config, but couldn't see the issue.

To rephrase: you config is okay. You should be fine.

Some hints to get it working. Since I don't understand why you have the issue, maybe the last hint is what you need?
- Maybe your config wasn't picked up by HA yet? When you do a Refresh (three dots menu in the upper right corner of the screen) the updated config will be used.
- `initial_auto_toggle_view: false` is exactly what should be used to turn off auto toggling through the views. You have this already in your config.
- `auto_toggle_view_period` can be omitted and the default of 10 seconds won't be used when you have `initial_auto_toggle_view: false`.
- `auto_toggle_view_period: 0` doesn't do anything. Zero seconds isn't possible and the default of 10 seconds will be used if you use also `initial_auto_toggle_view: true` of course.
- If the upper right auto toggle image is highlighted, the auto toggle feature is ON. If the image is grey, the feature is OFF.
- You have to click in the center of the card (click on the unit of measurement) to manually toggle between views. Don't use the upper right auto toggle image for that.

Please, let me know if you still can't turn off the auto toggling (= get the upper right auto toggle image in a grey color).

**Comment by PierreScerri** [comment]
Thank you for the explanation.  I had forgotten that you can switch views by clicking in the centre.  That is what I I was after.  Thanks for reminding me.

**Comment by gurbyz** [comment]
Glad it's solved.
