### ISSUE TITLE
Order of value and direction of arrows is wrong after upgrade to 2021.5

### ISSUE THREAD

**Issue by djoek** [gurbyz/power-wheel-card#77]
**Which version of HA do you use?**
2021.5.1

**Which version of the card do you use?**
0.1.5

**Describe the bug**
After upgrading to 2021.5, the wheel 'order' is wrong

**Configuration of the card**
```
type: 'custom:power-wheel-card'
solar_power_entity: sensor.pv_power_kw
grid_power_consumption_entity: sensor.power_consumption
grid_power_production_entity: sensor.power_production
debug: false
power_decimals: 3
production_is_positive: true
```

**Expected behavior**
correct value under correct icon, and arrows in the right direction

**Screenshots**
![image](https://user-images.githubusercontent.com/3184142/117679323-762db700-b1b0-11eb-96b6-399d409c81a4.png)

As you can see, 4150 should be under the sun, 2394 under the grid. Clicking the arrow pops up the correct value

**Comment by gurbyz** [comment]
Those values on your image look very strange indeed!

I don't think it's related to a bug in the code of the card or to you clicking on arrows, because the value under the sun icon isn't calculated but taken directly from the sensor. So, if you see that value changing, that means that the sensor value did change at that moment.

What could cause brief showing of unrealistic values, is that your sensors aren't updated at the same time. For a brief moment the calculations are based on e.g. the current solar power value but the grid power value of some seconds ago or vice versa. Possible reasons are: the sensors come from different devices or the update frequency of the sensors differs. Maybe (I'm just guessing here) the performance improvements of home assistent for the latest couple of their releases made the time difference of updating sensors more visible in your situation?

At the moment you took the image, your both grid sensors resulted to the export-to-grid value of 4150. The power can only come from your solar panels, so the value of your solar power sensor should have been 4150 or greather. But it was 2394.

**Comment by baccula** [comment]
I'm seeing what I believe is similar behavior on my system running HASS OS 2021.5.4 and the latest release of this card. In my case, I am seeing the grid value displayed on the grid and the home, with both of the upper arrows showing yellow as in the screenshot above. 

![image](https://user-images.githubusercontent.com/22080883/119441228-ff7dd700-bce2-11eb-89b9-278334d79ad3.png)

> type: 'custom:power-wheel-card'
>solar_power_entity: sensor.solaredge_ac_power
>grid_power_entity: sensor.utility_power
>debug: false

**Comment by djoek** [comment]
Hi all,

a quick update.  My issue stemmed from the fact that the data was collected from the SMA plugin,  which moved from manual .yaml file config to a 'full' integration.  This made some template variables that i use act up.  After cleaning up my config, and using the right "new" entities, all started working well.

As this is not a power-wheel-card issue, i'm closing the issue
